# -*- coding: utf-8 -*-
"""Age Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pU5jD-ygm1oDXpwoawC6CLEN3To4IHuo
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st
from datetime import date

st.title("Age Calculator")

dob = st.date_input("Select DOB")

if st.button("Calculate"):
  today = date.today()
  age = today.year - dob.year

  st.success(f"Age: {age} years")

