# -*- coding: utf-8 -*-
"""Grade Calculator(NO Keyboard Input).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W96DUQJsJHDAYoQjZzTOJXV0od3we29S
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Grade Calculator")
st.write("Slide to select your marks:")

marks = st.slider("Select your marks out of 100", min_value = 0, max_value = 100, value = 50)

if st.button("Calculate Grade"):
  if marks >= 90:
        grade = "A+"
        st.success(f"Excellent! Your grade is {grade}")
  elif marks >= 80:
    grade = "A"
    st.success(f"Great job! Your grade is {grade}")
  elif marks >= 60:
    grade = "B"
    st.info(f"Good! Your grade is {grade}")
  elif marks >= 40:
    grade = "C"
    st.warning(f"You passed. Your grade is {grade}")
  else:
    grade = "Fail"
    st.error(f"Work harder next time. You are {grade}")

