# -*- coding: utf-8 -*-
"""Online Petition Form.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXqTcl4G-_p2dOQ9W7ZVxnyluVWv0B3x
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Online Petition")
st.header("Pettiton for the resignation of Dharmendra Pradhan, Education Minister of India.")

st.write("Please fill out the form below to sign the petition.")

raw_name = st.text_input("Enter your full name:")

name_uppercase = raw_name.upper()

signature = st.text_input("Enter your signature (Text):")

if st.button("Sign Petition"):
  if name_uppercase != '' and signature != '':
    st.success("Thank you for signing!")
    st.write("Submitted Details:")
    st.write(f"Name: {name_uppercase}")
    st.write(f"Signature: {signature}")

  else:
    st.warning("Please fill in both fields before signing.")

