# -*- coding: utf-8 -*-
"""Student Name List Collector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1v-0TJnD-6yDw8vdg8EG7QAUdqc9577
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Class Student List")

if "student_list" not in st.session_state:
  st.session_state.student_list = []

new_student = st.text_input("Enter student Name:")

if st.button("Add Student"):
  if new_student != '':
    st.session_state.student_list.append(new_student)
    st.success(f"{new_student} has been added to the list!")
  else:
    st.warning("Name cannot be empty!")

st.write("---")
st.write("All Submitted Names:")

if len(st.session_state.student_list) == 0:
  st.info("No students added yet.")
else:
  for index, name in enumerate(st.session_state.student_list):
    st.write(f"{index + 1}. {name}")

