# -*- coding: utf-8 -*-
"""Student Course Registration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnlmEI_fcy-S1umtGDzTSu9pjECOCEXU
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Student Course Registration")

course = st.selectbox("Select Course",
 ["BCA","BBA", "MBA", "MCA", "Other"])

if course == "Other":
  name = st.text_input("Enter your Course name")

if st.button("Submit"):
  st.write("Your Course is Submitted")
  st.write(f"Your Course is {course}")

