# -*- coding: utf-8 -*-
"""Student Information.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRGGvt9pQ8fk0eNaGQxEbH9md0_xqSER
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st
st.title("Student Information System")
st.write("Enter student details and view the submitted information.")

name = st.text_input("Student Name")
roll = st.number_input("Roll Number", min_value=1)
course = st.selectbox("Select Course",["BSc Data Science", "BCA", "BTech", "BCom"])
subjects = st.multiselect("Select Subjects",["Python", "Java", "DBMS", "ML", "Statistics"])
marks = st.slider("Marks", 0, 100, 50)

if st.button("Submit"):
    if name == "" or len(subjects) == 0:
        st.error("Please fill all required fields.")
    else:
        st.success("Student details submitted successfully!")
        st.subheader("Submitted Information")

        st.write(f"**Name:** {name}")
        st.write(f"**Roll Number:** {roll}")
        st.write(f"**Course:** {course}")
        st.write(f"**Subjects:** {', '.join(subjects)}")
        st.write(f"**Marks:** {marks}")

