# -*- coding: utf-8 -*-
"""Table Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHozrQGcNeIeG8OFhjvQUYsMvVPtai9m
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Table Generator")

number = st.number_input("Enter a number to generate its table:", value = 1, step = 1)

if st.button("Generate Table"):
  st.write(f"Multiplication Table of {number}")

  for i in range(1, 11):
    st.write(f"{number} x {i} = {number * i}")

