# -*- coding: utf-8 -*-
"""To Do List App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CB2Es0fbR_FfIYdeRADSCfpIvtJtYI-I
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
# import streamlit library and give it short name "st"
import streamlit as st

# Creates main heading an webpage
st.title("To Do App")

# Check whether "tasks" list already exists
# in streamlit session memory
if "tasks" not in st.session_state:

  # create an empty list for storing tasks
  st.session_state.tasks = []

# Create a text box to type task
# Store entered text inside variable task
task = st.text_input("Task")

# Create Add button
# Code runs only when button is clicked
if st.button("Add"):

  # Add entered task into task list
  st.session_state.append(task)

# Loop through every task in task list
for t in st.session_state.tasks:

  # Display task with check mark
  st.write("✅",t)

